before_script:
  - export DISPLAY=:99.0
  - export $(dbus-launch)
  - export NSS_USE_SHARED_DB=ENABLED
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 10
  - node_modules/.bin/buster-server &
  - sleep 5
  - firefox http://localhost:1111/capture &
  - sleep 5


script:
  - "npm test"

language: node_js

node_js:
  - 0.8